### ISSUE TITLE
small typo

### ISSUE THREAD

**Issue by akumaaayush** [Hungerarray/signalR-omagol#28]
https://github.com/Hungerarray/signalR-omagol/blob/fdf608d820f3c056c5dca12c1c21188c48af5711/Frontend/Dockerfile#L6

./

**Comment by Hungerarray** [comment]
This is intentional to have layer caching to ensure we won't have to pull down npm packages everytime there is change on source files.

**Comment by Hungerarray** [comment]
Added the mutliple file addition fix. This had not given any issues on my side so went under the radar. Thanks for pointing it out.
